services:
  - type: worker
    name: restapi
    repo: https://github.com/MUSTAFA-A-KHAN/funny-telegram-bot.git
    plan: free
    branch: main
    runtime: go
    startCommand: ./funny-telegram-bot
    buildCommand: |
      go mod tidy
      go build
